### ISSUE TITLE
content not rendering

### ISSUE THREAD

**Issue by Lwweaves** [seejamescode/global-upvote#1]
Hi there,

First off, thanks for sharing this. I just finished reading your freeCodeCamp/Medium post and this is pretty neat.

Just trying to get this up and running locally and I can't figure out why the reddit content isn't rendering on the page. Just looks like this-- https://prnt.sc/go2lb9

I added the keys.json file, added to the root, created my app in reddit's api settings, and plugged in the info. I tried creating a couple different app types (web app, personal use script) but that doesn't seem to help. I could be off in thinking that this is the problem, but that's my guess.

I'm a total newb so thanks for your patience and help! Again, really neat app.

**Comment by seejamescode** [comment]
Glad you like it, but let's figure out why it isn't working for you!

I did use the personal script option for Reddit.

Add some console logs and let me know what data is logging:
- To find out if you get the collection of stories from Reddit to your server...  https://github.com/seejamescode/global-upvote/blob/master/server.js#L84 (`console.log(posts)`)
- To find out if you get the comments for each story from Reddit to your server... https://github.com/seejamescode/global-upvote/blob/master/server.js#L36 (`console.log(post)`, but just share one result)
- To find out if you get the posts from your server to your UI... https://github.com/seejamescode/global-upvote/blob/master/src/App.js#L179 (`console.log(response.stories)`)

**Comment by Lwweaves** [comment]
Thanks so much for responding to this man. I feel silly but I actually got it working. I just needed to wait until Reddit approved my API access. I didn't see that link in the instructions at first saying that you need to submit your app for review. Once they approved it, it worked. Thanks again.
